---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I want to be your motivation, inspiration, and everything   in between.  
I want to be the reason for your smile, the one who turns   your frown upside down.  
I want to be the one you look up to and admire and the one   you desire.  
The voice in your heart, not your ear, telling you   everything that you need, not want to hear.  
I want to mean enough to you to be your solution to all   life's ups and downs.  
I want you to need me every morning when you wake up,   during the day when you have had enough.  
I want to feel your excitement to kiss me good night after   your day has been so rough.  
I need and want all these things from you because you're   the only one who gets me through.  
I love you more and more each day, it's true.  
You have blessed me with a beautiful life, made together   by both of us.  
I need all these things from you because my most treasured title is your wife.


